### ISSUE TITLE
Updatable minter

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/cw-nfts#108]
Had a creator contact me about being able to update the minter. I propose we use `cw-ownable` for this.

Wondering if this is something we want to include in `cw721-base` or no?

**Comment by huawesome** [comment]
It seems very useful to be able to grant temporary minting rights to dapps, or even just move wallets, and if there is no "official" solution a lot of people are going to take their best shot at it. Granted this is not always bad, but I think it would be better if there is a "safe" solution designed by the core team and distributed as part of base instead of it being something people kluge on as they are learning. 

Edit: I think I misunderstood what a minter was in this context

**Comment by JakeHartnell** [comment]
> It seems very useful to be able to grant temporary minting rights to dapps, or even just move wallets, and if there is no "official" solution a lot of people are going to take their best shot at it. Granted this is not always bad, but I think it would be better if there is a "safe" solution designed by the core team and distributed as part of base instead of it being something people kluge on as they are learning.

I think that could be a good example to build. Should be a separate issue though? Do you mind making one and trying to be as descriptive as possible about the use case?

**Comment by yubrew** [comment]
Is this not possible through authz? Give limited message rights to dapp or other wallet?On Feb 18, 2023, at 2:35 PM, Jake Hartnell ***@***.***> wrote:﻿

It seems very useful to be able to grant temporary minting rights to dapps, or even just move wallets, and if there is no "official" solution a lot of people are going to take their best shot at it. Granted this is not always bad, but I think it would be better if there is a "safe" solution designed by the core team and distributed as part of base instead of it being something people kluge on as they are learning.

I think that could be a good example to build. Should be a separate issue though? Do you mind making one and trying to be as descriptive as possible about the use case?

**Comment by JakeHartnell** [comment]
> Is this not possible through authz? Give limited message rights to dapp or other wallet?On Feb 18, 2023, at 2:35 PM, Jake Hartnell ***@***.***> wrote:﻿ It seems very useful to be able to grant temporary minting rights to dapps, or even just move wallets, and if there is no "official" solution a lot of people are going to take their best shot at it. Granted this is not always bad, but I think it would be better if there is a "safe" solution designed by the core team and distributed as part of base instead of it being something people kluge on as they are learning. I think that could be a good example to build. Should be a separate issue though? Do you mind making one and trying to be as descriptive as possible about the use case? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

On second look, I think this will work in the latest `wasmd` version: https://github.com/CosmWasm/wasmd/pull/1077

**Comment by huawesome** [comment]
> I think that could be a good example to build. Should be a separate issue though? Do you mind making one and trying to be as descriptive as possible about the use case?

Sorry I wasn't clear at all. What I meant is that the use case I attempted to describe and a few others would be solved if the minter was undateable. I was also suggesting that the functionality be included in base because it seems like a common ask, and it might prevent some mistakes.

**Comment by yubrew** [comment]
https://github.com/CosmWasm/cw-nfts/blob/main/contracts/cw721-base/src/msg.rs#L4
already merged in :)

**Comment by JakeHartnell** [comment]
Closed with: https://github.com/CosmWasm/cw-nfts/pull/109
