### ISSUE TITLE
Consider using Uint256Key for Token IDs

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/cw-nfts#5]
Continuing a discussion from Discord: https://discord.com/channels/737637324434833438/892092030870749214/892537033208254465

What do we want for Token IDs?

Currently, they are strings. @shanev brought up the point that "now with the existence of Uint256Key, there might be a better case for using it just like ERC-721". He also added:
> Because can run into iteration issues in the store if they can be arbitrary strings no?

Personally, I've come across this recently with the `all_tokens` query when there are different token ids like `"1"` and `"uuid-43123d-eaGg3Xz"`.

@ethanfrey brought up some good questions:
> Having them all the same length may make enumeration nicer (alphabetical), but do you really want them encoded as integers ("183836284794036363790202743525168039373")?
> or rather hex encoded bytes?
> or enforce this is ascii and right pad with spaces?

So hence this ticket. 

`Uint256Key` seems to make sense for me, but curious what others think. CC @ben2x4, @alwin-peng, @the-frey.

**Comment by the-frey** [comment]
Forgive me for the potentially stupid question - but is iteration a common use case? As in, in the order of creation? I would have thought that unordered would be the general case, as per most k/v style structures... 

I'd have thought that access by key was super common, access all was somewhat common (but probably costly) and that ordering might not be an issue in the second case.

Unless of course there's some blocker to iteration caused by not being exactly a certain format, which may be what was meant by  

> Personally, I've come across this recently with the all_tokens query when there are different token ids like "1" and "uuid-43123d-eaGg3Xz".

(deserialisation into diff types throwing an error?)

**Comment by ethanfrey** [comment]
access by key is the most common and only supported case on Ethereum.

You can list all tokens or all tokens by owner. These keys are ordered by (length, token_id as bytes). This means "zoo" is before "food". But do we really care about the ordering?

If we made this something like `bytes[32]` that contains a string and right padded it with 0's, the length ordering issue wouldn't be a problem. However, it would still sort on ASCII / UTF8 code point. Such that "Z" (0x5a) would be before "a"  (0x61). Add utf-8 and it gets more confusing. This is the same issue on any database with LOCALE="C" which is the only efficient string compare one.

In general, I am suspect of using Uint256 anywhere. People use that in Ethereum everywhere as they don't really have other types (everything ends up as 32 bytes). We found that no coin ever made needs more than Uint128 to store trillions with 18 decimal places, so use that instead for the Coin type. Likewise, if people shove a uff-8 string into `Uint256` or `bytes[32]` as they don't have variable length strings, that is not a reason to do the same.

We can keep compatibility with Ethereum, but let's pick the right types for the job

**Comment by ben2x4** [comment]
I agree with Ethan that ethereum abuses the u256 type and we should not use it unless we have a valid reason. In this case our only concern is the NFT contract has enough available unique IDs. 

Having dealt with way too many ID collision bugs, my personal preference is to actually remove ID from the mint msg and just have it auto increment with each mint. The u128 type would be more than sufficient, honestly u64 is good enough as that would allow 18 quintillion unique nfts. 

If someone wants to store a custom ID on the nft they can include that as an extension and implement their own custom checks around it. This feels like better architecture, makes it easier for projects that don't need to customize the ID, and standardizes what ID is for all projects.

**Comment by the-frey** [comment]
Rather than incrementing, isn't generating a uuid a better identifier in that case? Guarantees uniqueness, unguessable, clients can't just go `-1` on a given thing to try their luck at doing Naughty Things™️ 

Although I guess that would then deserialise to a string, and then we're into the Stringly Typed hellscape p fast

ETA: apologise in advance for the fact most of my design choice questions are posed this way :)

**Comment by iLoveBusinessDevelopment** [comment]
I'm for leaving it as a String. It's a superset of Uint256, if you want portability with ETH you can have that by using a string representation of a  Uint256. There are some nice use cases for a string token id, for example if you're setting up a name service, and you want to use NFTs to represent domains, saving the domain as a token id makes perfect sense. I'd rather give the user freedom than enforce Uint256, which seems pretty arbitrary

**Comment by shanev** [comment]
Thanks for chipping in everyone! Ordering isn't that important. Clients that need ordering can (and probably should) implement some sort of indexer and API around contract data anyway. As @ethanfrey said, this contract is already doing more than Ethereum.

Uint256 is a waste of space and the current `Vec<u8>` approach is very efficient and an improvement over Ethereum. No need to maintain parity with ERC-721 if we have a chance to improve on it. Really like @ben2x4's suggestion of making it a `u64` and auto-incrementing. But also like the flexibility of the current approach for uses cases like what @alwin-peng mentioned.

I'm for keeping it as is, because pretty much everything else is a subset of it. Leaving incrementing up to the client / minter also fits in with how things already work in Ethereum and in Cosmos (i.e: account sequence number).

**Comment by JakeHartnell** [comment]
Some pretty convincing arguments @alwin-peng / @shanev / @the-frey / @ethanfrey / @ben2x4. I think I'm convinced to leave it as it, but I'm glad we had this discussion. Thank you all!

Going to close this issue, but feel free to reopen if you feel strongly or add additional closing thoughts for posterity.
